// Assignment Code
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
// Criteria 1: Create a popup that appears when the user clicks on the page button
// Criteria 2: Create a series of prompts where the user is asked to select specificaitons for the type of password generated by the app.
// Criteria 3: Prompts should included questions about password length (8-128), lower case, upper case, special characters and numbers
// Criteria 4: The prompt concerning length is mandatory to fill out. In addition, at minimum one of the other specifications must be filled out for the application to create a password.
// Criteria 5: Generated password must inlcude examples of all selected password specification.
// Criteria 6: Generated password must appear either on the screen in the premade password box or in an alert box

